---
title: "Info Distributions"
output: html_fragment
---
## Manual
For general information on this shiny app, click the right-most tab 'Info' at the top of this app. 

## Options 

- **Variance or ICC:** Choose to manipulate the variances or intra-class correlations of the variable.

***Variance option chosen:***
- **Within-person Variance** Change the values of the within-person variance for the variable. 

A within-person variance is the variance taken over the repeated measures of one person. Here, we assume that this variance is the same for all persons (or, you can consider this value as the average within-person variance, the average taken over all possible persons - this would give the same results here). 

- **Between-person Variance**
Change the values of the between-person variance for the variable. 

Imagine each person has their own mean for the variable (e.g., if we were to track each person's scores over time, and for each person calculate their average score). The between-person variance is the variance of the means of different persons.

***ICC option chosen:***
- **ICC of X; ICC of Y:** Change the intra-class correlation of the variable. 

The ICC is the the proportion of between-person variance to the total variance of the variable. The larger the ICC, the larger the between-person variance, and the smaller the within-person variance.




## Results
For simplicitly, all distributions are centered around a mean of zero.

### Between-person Density (top-left) 
The centered, normal density of the means (expected values) of different persons (e.g., persons) for the variable of interest. That is, if we were to track the scores of different persons over time for the variable, then the means of those scores for each person form the basis of this normal distribution.

At the top of the distribution the true value of the between-person variance is displayed (chosen by the user).

### Within-person Density (top-right) 
The centered, normal density of a person's scores on the variable at different points in time (e.g., one person's repeated measures). We assume here for simplicity that the within-person density is equal for all persons. (Or, you can consider this as the within-person distribution of an average person - this would give the same results here). 

At the top of the density the true value of the within-person variance is displayed (chosen by the user).

### Cross-sectional Density (bottom)
The centered, normal distribution that would result for the scores of different persons (e.g., persons) at a specific point in time (for example, time point 25), given the specified within-person and between-person densities. 

At the top of the density the true value of the cross-sectional variance is displayed, equal to the sum of the within-person and between-person variance. 



