---
title: "Info"
output: html_fragment
---
### A Within/Between Problem Primer and App
This Shiny app accompanies the in preparation manuscript "A "Within/Between Problem" Primer: *About (not) separating within-person variance and between-person variance in psychology*." by N. K. Schuurman (2023). 

The pre-print manuscript is available at <a href="https://psyarxiv.com/7zgkx">psyarxiv</a>.

The source code for this app can be found at <a href="https://github.com/NKSchuurman/WithinBetweenApp">GitHub</a> and at the <a href="https://osf.io/j4rk3/">Open Science Framework</a>.

#### Contact information
If you have any questions or comments, please contact No&#233;mi K. Schuurman (N.K.Schuurman at uu.nl).

#### Citing the App
Schuurman, N. K. (2022). *A Within/Between Problem App* [Shiny application version 1.0]. https://osf.io/j4rk3/
  
```{latex eval = F}
@Manual{,
  title = {A Within/Between Problem App},
  author = {N K Schuurman},
  year = {2022},
  note = {Shiny application version 1.0},
  url = {https://osf.io/j4rk3/},
}
```

#### Citing the accompanying Manuscript
Schuurman, N. K. (2023). *A "Within/Between Problem" Primer: About (not) separating within-person variance and between-person variance in psychology.* PsyArXiv. 

```{latex eval = F}
@Unpublished{,
  title = {A Within/Between Problem Primer: About (not) separating within-person variance and between-person variance in psychology.},
  author = {N K Schuurman},
  year = {2023},
  note = {PsyArXiv}
  }
```