---
title: "Info"
output: html_fragment
---
## Manual
For general information on this shiny app, click the right-most tab 'Info' at the top of this app. 

## Options 

- **ICC or Standard deviation:** Choose to manipulate the intra-class correlations or standard deviations of variables X and Y (see below).

- **Within-subject correlation:** Change the value of the within-subject correlation.
- **Between-subject correlation:** Change the value of the between-subject correlation.
- **N for plot:** Change the sample size for the scatter plots. Does not affect the value of the depicted correlations, as these are all population values.

***ICC option chosen:***
- **ICC of X; ICC of Y:** Change the intra-class correlation of variable X or Y respectively. The ICC is the the proportion of between-subject variance to the total variance for that variable.

***SD option chosen:***
- **Within-subject sd of X; of Y; Between-subject sd of X, of Y:** Change the values of the standard deviations of either the within- or between-level variables for variable X or Y.


## Results

### Between-subject Correlation (top-left) 
The between-subject correlation indicates whether a subject that has a relatively high/low mean on X compared to other subjects, also has a relatively high/low mean on Y compared to other subjects. 

At the top of the scatter plot the true value of the between correlation is displayed (chosen by the user).

The data points in this plot are the the expected values for variables X and Y of different subjects. That is, if we were to track the scores of a subject over time for variables X and Y, then the two means of those scores (one for X and one for Y) are depicted as one datapoint in the scatter plot.

### Within-subject Correlation (top-right) 
The within-level correlation indicates whether a subject that currently has a relatively high/low score for X compared to their average score, also tends to have a relatively high/low score for Y compared to their average score. We assume here for simplicity that the within-subject correlation is equal for all subjects.

At the top of the scatter plot the true value of the within correlation is displayed (chosen by the user).

The data points in this plot are the scores for X and Y of one subject at different points in time.

### Cross-sectional Correlation (bottom)
The cross-sectional correlation that would result given the specified within-subject and between-subject correlations and ICCs/standard deviations. 

This correlation indicates, for one point in time, whether subjects that have a relatively high/low scores for X compared to other subjects, also tend to have a relatively high/low scores for Y compared to other subjects. 

At the top of the scatter plot the true value of the cross-sectional correlation is displayed (this is the population value, and hence is not impacted by sampling errors).

The data points in the scatterplot (depicted in purple) are scores of different subjects - each subject has their own data point - for variables X and Y at one specific  time point in time (a cross-sectional design). Their purple color turns more towards red, or more towards blue, depending on whether the correlation is closer to the between or within correlation respectively.


